### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by uringlas** [LeagueOfPoro/EsportsCapsuleFarmer#18]
The exe sometimes just crashes. I could not reproduce the error.  Sometimes it happens after 5 min sometimes after 12 hours. No pattern can be seen.

Version 2.1
headless: false
autologin: false
OS: Win10
self compiled: false

Traceback (most recent call last):
  File "main.py", line 128, in <module>
  File "selenium\webdriver\remote\webdriver.py", line 447, in get
  File "selenium\webdriver\remote\webdriver.py", line 435, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 247, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: cannot determine loading status
from unknown error: unexpected command response
  (Session info: chrome=103.0.5060.114)
Stacktrace:
Backtrace:
        Ordinal0 [0x007E56B3+2184883]
        Ordinal0 [0x0077E5F1+1762801]
        Ordinal0 [0x00693DA8+802216]
        Ordinal0 [0x006871FE+750078]
        Ordinal0 [0x0068673A+747322]
        Ordinal0 [0x00685D1F+744735]
        Ordinal0 [0x00684C08+740360]
        Ordinal0 [0x00685208+741896]
        Ordinal0 [0x0069CB32+838450]
        Ordinal0 [0x0069628B+811659]
        Ordinal0 [0x00695E05+810501]
        Ordinal0 [0x006964E3+812259]
        Ordinal0 [0x0068F645+783941]
        Ordinal0 [0x0068F2CD+783053]
        Ordinal0 [0x00699FCB+827339]
        Ordinal0 [0x0069D320+840480]
        Ordinal0 [0x006854D6+742614]
        Ordinal0 [0x00699C07+826375]
        Ordinal0 [0x006ED292+1168018]
        Ordinal0 [0x006DC926+1100070]
        Ordinal0 [0x006B6EA0+945824]
        Ordinal0 [0x006B7D96+949654]
        GetHandleVerifier [0x00A84192+2704034]
        GetHandleVerifier [0x00A7687D+2648461]
        GetHandleVerifier [0x0087119A+529066]
        GetHandleVerifier [0x00870006+524566]
        Ordinal0 [0x00784F2B+1789739]
        Ordinal0 [0x00789978+1808760]
        Ordinal0 [0x00789A65+1808997]
        Ordinal0 [0x00792A01+1845761]
        BaseThreadInitThunk [0x76FCFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77757A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77757A6E+238]

[7344] Failed to execute script 'main' due to unhandled exception!

**Comment by LeagueOfPoro** [comment]
This is a known issue with Chrome 103 which is fixed in 104. It is explained in the tutorial video
