### ISSUE TITLE
Cannot set the Twitch player quality. Is the match on Twitch?

### ISSUE THREAD

**Issue by TheFeelTrain** [LeagueOfPoro/EsportsCapsuleFarmer#19]
For some games (particularly CBLOL and LLA it seems) they start the YouTube streams before the Twitch streams. When the farmer tries to open them you get this error:

```
WARNING:League of Poro:Cannot set the Twitch player quality. Is the match on Twitch?
``` 

From here it gets stuck on the YouTube streams. The videos don't autoplay so the rewards indicator is a red X. I am wondering if it would be possible to automatically refresh the page after this error is detected and/or switch to the Twitch URL somehow. Maybe even just close the page so that it reopens the next time it checks for streams. Thanks!

**Comment by LeagueOfPoro** [comment]
The program tries to force Twitch every time for known URLs. I am extending the list continuously as I see the matches.
