### ISSUE TITLE
Automatically lower the quality of the streams

### ISSUE THREAD

**Issue by JonasTD** [LeagueOfPoro/EsportsCapsuleFarmer#2]
As we're not actively watching the streams I feel it should auto lower the stream quality.
https://dev.twitch.tv/docs/embed/video-and-clips/
setQuality(quality:String):void

**Comment by LeagueOfPoro** [comment]
I cannot find a way to directly interact with the Twitch player. This feature might come in the future though

**Comment by JonasTD** [comment]
Hmm I see, I'll try to look into it myself if there's any option we can make this work!
