### ISSUE TITLE
TCL issue

### ISSUE THREAD

**Issue by Denialxx** [LeagueOfPoro/EsportsCapsuleFarmer#32]
Not sure exactly what the issue is. It seems like the program is grabbing a bad link for the TCL. so refreshing it when rewards are not eligible will not fix the issue. 

A small recommended fix is for the program to close the tab after failing 4 retry for rewards. so on the next cycle it will attempt to reopen the tab with the correct link. (issue with this is it would always do this for youtube sources)

Thanks for all the hard work!

**Comment by Denialxx** [comment]
To add on, closing and reopening fixes the issue but not ideal

**Comment by auroraisluna** [comment]
Is this happening at some particular stream or everyone?

**Comment by auroraisluna** [comment]
Update to 3.2, fixes the URL.
