### ISSUE TITLE
Unable to create file: -4 & Failed to save user data

### ISSUE THREAD

**Issue by onsraxo** [LeagueOfPoro/EsportsCapsuleFarmer#33]
been getting these two errors constantly for days now and I am not sure if it interferes with the functionality of the program:

`[0731/233149.621:ERROR:backend_impl.cc(756)] Unable to create file: -4
[0731/233149.621:ERROR:entry_impl.cc(1001)] Failed to save user data`

![image](https://user-images.githubusercontent.com/74201649/182047607-0dd3a496-9ba1-4562-a333-3e05acd1c08b.png)

**Comment by LeagueOfPoro** [comment]
Just a chrome error, you can ignore it. Try to restart the program, it might disappear.
