### ISSUE TITLE
multi-capsulefarmer freezes

### ISSUE THREAD

**Issue by onsraxo** [LeagueOfPoro/EsportsCapsuleFarmer#34]
sometimes singular instances of the capsulefarmer freeze when opening multiple (3 in my case) at the same time. it stays stuck at "Logging in".

![image](https://user-images.githubusercontent.com/74201649/182816035-e2d0fc4f-c460-4f47-beef-1b79afe0c348.png)

**Comment by auroraisluna** [comment]
Can not replicate using 3 and 4 tools. Perhaps you got ratelimited temporarily?
