### ISSUE TITLE
Is it feasible to add 32bit support?

### ISSUE THREAD

**Issue by Hentaisocial** [LeagueOfPoro/EsportsCapsuleFarmer#37]
I have an old Atom tablet that would be perfect to run the farmer 24/7 drawing trivial amounts of electricity. I understand this is maybe a niche use case so it may not be worth doing if it's nontrivial.

**Comment by LeagueOfPoro** [comment]
Use it directly through Python. See [https://github.com/LeagueOfPoro/EsportsCapsuleFarmer#installation-advanced](https://github.com/LeagueOfPoro/EsportsCapsuleFarmer#installation-advanced)
