### ISSUE TITLE
handshake failed error

### ISSUE THREAD

**Issue by FaZemoji** [LeagueOfPoro/EsportsCapsuleFarmer#52]
Hi,

I'm getting an error but the program seems to be working? Here's what the error looks like : 

> [0902/190351.144:ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -202

Its spamming this every 30 seconds. 

EDIT : This is what my terminal looks like when i run the program 
![image](https://user-images.githubusercontent.com/80038169/188204066-8ff221a9-2b04-4e82-a760-f2db4b942395.png)

**Comment by auroraisluna** [comment]
Very strange. Which region are you on? Can you access https://lolesports.com/ fine from your own browser? Is chrome updated?

**Comment by LeagueOfPoro** [comment]
It's not great, but it looks like the functionality is not affected.

**Comment by FaZemoji** [comment]
> Very strange. Which region are you on? Can you access https://lolesports.com/ fine from your own browser? Is chrome updated?

I'm in EUW, i can acces lolesport without any problem and my chrome is on 105



> It's not great, but it looks like the functionality is not affected.

idk if its worth it trying to fix it or not

**Comment by LeagueOfPoro** [comment]
There's nothing to fix on our end. Are you using proxy or vpn? This kinda looks like [MiTM](https://en.wikipedia.org/wiki/Man-in-the-middle_attack)

**Comment by FaZemoji** [comment]
OK, so you were right, i'm using a thing called NextDNS it blocks things like ads and tracking on my router. I disabled it and now i dont have the message anymore!

**Comment by auroraisluna** [comment]
This could be a good resource to add a troubleshooting message if this error is detected. For example: 
"SSL error [...] Are you using a VPN, Proxy or an Ad blocker?" 

@LeagueOfPoro what do you think?
