### ISSUE TITLE
Add colors to some interactions

### ISSUE THREAD

**Issue by aLonelyNetu** [LeagueOfPoro/EsportsCapsuleFarmer#53]
Hey hello, can some interactions have colors like:

log.info(f"{match} is eligible for rewards ✓") maybe can be green;
log.info(f"{match} is not eligible for rewards. Retrying...") maybe can be orange or yellow;
log.warning(f"{match} is not eligible for rewards") maybe can be red;

Thanks. 😄

**Comment by MrBartusek** [comment]
This project could actually use a logs overhaul

**Comment by aLonelyNetu** [comment]
Actually not that bad:

![CapsuleFarmer_Yg1SRSHGtz](https://user-images.githubusercontent.com/77209536/189491384-2ab6cadd-9d45-49e4-8b3a-8673c7cf3366.png)

**Comment by dimitrisz123** [comment]
is there anyone working on this? i want to try

**Comment by LeagueOfPoro** [comment]
Not that I know of. Have fun!
