### ISSUE TITLE
Video is not considered started and Reward are not eligible because of that

### ISSUE THREAD

**Issue by a-Datana** [LeagueOfPoro/EsportsCapsuleFarmer#54]
Starting the currently latest version (3.1) 
Reward are enabled as soon as the player is separately activated - Headless mode has no functionality in this case.

**Comment by MrBartusek** [comment]
Rewards for european masters are not working but only in headless. Otherwise works as intended.

**Comment by MrBartusek** [comment]
> Try updating to 3.2 and see if this keeps happening.

I was testing this on master yesterday and it was not working correctly

**Comment by MrBartusek** [comment]
Thanks! It works great
