### ISSUE TITLE
instant crash

### ISSUE THREAD

**Issue by Viciboom1** [LeagueOfPoro/EsportsCapsuleFarmer#55]
whenever i try to run the program it crashes/closes after 1 or 2 seconds. i've tried reinstalling it and modifying my config but nothing seems to fix it. I've used it for a week before and it was working fine.

**Comment by LeagueOfPoro** [comment]
Most likely currently unsupported version of a browser. Try edge or firefox. Add this to your config:
```yaml
browser: firefox
```
or
```yaml
browser: edge
```

**Comment by Viciboom1** [comment]
it worked! thanks so much
