### ISSUE TITLE
Password with special characters make file type invalid

### ISSUE THREAD

**Issue by josephisticated** [LeagueOfPoro/EsportsCapsuleFarmer#57]
![image](https://user-images.githubusercontent.com/53388005/190924955-f09bf649-5e62-4981-9fc1-4de47f33be5a.png)
My password has the character "@" in it and it causes the configuration file to become invalid.

**Comment by josephisticated** [comment]
Tried it with another account that doesn't have a special character in it.

**Comment by LeagueOfPoro** [comment]
Try to put quotes around it:
`"P@ssword"`

**Comment by LeagueOfPoro** [comment]
Did it work?

**Comment by auroraisluna** [comment]
I can replicate the issue, wrapping in quotes fixes it.
