### ISSUE TITLE
worlds is not eligible for rewards

### ISSUE THREAD

**Issue by MrBartusek** [LeagueOfPoro/EsportsCapsuleFarmer#63]
![image](https://user-images.githubusercontent.com/23432278/193123837-72f0e207-6e16-4c94-9b77-8dc2816294b2.png)

**Comment by dangledoodles** [comment]
I got this same issue on 3x accounts

**Comment by LeagueOfPoro** [comment]
Override `https://lolesports.com/live/worlds` to `https://lolesports.com/live/worlds/riotgames`. I will fix it for the next match day

**Comment by LeagueOfPoro** [comment]
Fixed in v3.5
