### ISSUE TITLE
Stuck on youtube, wont switch to twitch upon refresh

### ISSUE THREAD

**Issue by Denialxx** [LeagueOfPoro/EsportsCapsuleFarmer#64]
![image](https://user-images.githubusercontent.com/108993401/193130666-bf56265d-bfec-4be9-b650-b136b525ef3e.png)

**Comment by Axel3026** [comment]
In your lol esport account go to settings and put twitch as default
![Screenshot_1](https://user-images.githubusercontent.com/87623383/193131291-4c8641a1-ba6d-4f17-921d-1b5f056b9ae8.png)

**Comment by Denialxx** [comment]
Thank you!
