### ISSUE TITLE
Alternative Chromium Browser Support

### ISSUE THREAD

**Issue by Linyoa** [LeagueOfPoro/EsportsCapsuleFarmer#66]
Hi,

Love the program, I'd hoped someone would make something like it for a while now and this is perfect.
Would it be possible, given that it's designed primarily for google chrome, to add support for other chromium based browsers? I personally use Vivaldi and it would be great not to have to leave chrome running just for this, but I have no idea how complicated or not adding other chromium browsers would be.

Thanks!

**Comment by xMatador-Git** [comment]
U can hardcode it to use chromium (works on my raspberry pi)
u need to replace _line 46_ with
`service = ChromeService('PATH TO UR CHROMIUM')`
for me in my raspberry pi it is _/usr/lib/chromium-browser/chromedriver_
so i had to change it to this for chromium
`service = ChromeService('/usr/lib/chromium-browser/chromedriver')`

**Comment by Linyoa** [comment]
Awesome, I was hoping it would be as easy as pointing it in the direction of a different directory, thanks @xMatador-Git
