### ISSUE TITLE
it's throwing me that error

### ISSUE THREAD

**Issue by Axel3026** [LeagueOfPoro/EsportsCapsuleFarmer#68]
![Screenshot_1](https://user-images.githubusercontent.com/87623383/193360929-3e28432b-7cdc-4048-8d6a-ca2c78a558c8.png)

**Comment by MrBartusek** [comment]
Yeah i also get that sometimes, seams to be random

**Comment by LeagueOfPoro** [comment]
It's a browser error, and it does not affect functionality.
