### ISSUE TITLE
Suggestion: force close on error (also, 69th issue; nice)

### ISSUE THREAD

**Issue by JonasTD** [LeagueOfPoro/EsportsCapsuleFarmer#69]
When the program runs into an error instead of spamming the console over and over again; let it close and create an error.txt file with the error reason.

I noticed that the program uses a lot of resources when it runs into an error and this could help prevent that.

Additionally it could read the contents of the error.txt file on next startup and display it in the dialog window.

EDIT: spelling

**Comment by a-Datana** [comment]
Personally Force restart on error would sound alot nicer

**Comment by JonasTD** [comment]
> Personally Force restart on error would sound alot nicer

perhaps as an option to toggle but I feel this could result in an endless loop.

**Comment by LeagueOfPoro** [comment]
I tried to do this in a different project and it was a pain. The browser would often not close at all, hogging resources.
