### ISSUE TITLE
Closing Capsule Farmer opens a Chrome instance that can't be closed. (Doesn't happen in adm mode).

### ISSUE THREAD

**Issue by JoaoVictorDaijo** [LeagueOfPoro/EsportsCapsuleFarmer#70]
When I close the Capsule Farmer, it opens a black Chrome window. If I try to close this window it reopens instantly, even if I try to finish the process with Task Manager it reopens again.

Each time I close the farmer it opens a new Chrome instance. I tried to do a manual breakpoint and check if closing the farmer early prevents this behavior.

As soon as this 'Devtools listening' logs the behavior happens.
![image](https://user-images.githubusercontent.com/33362807/193442174-24d4c9a4-5232-42ab-89b2-89f0b4208d1e.png)

![image](https://user-images.githubusercontent.com/33362807/193442262-a5e7530f-28f6-4fd1-b0af-f78b3f4b8363.png)

![image](https://user-images.githubusercontent.com/33362807/193442287-0664ce85-3255-4a8a-bbc4-9b772f135ab3.png)

I'm using the program in headless mode; the issue does not happen if I execute it in Administrator Mode.

**Comment by LeagueOfPoro** [comment]
Hmm, I cannot reproduce it. A temporary workaround would be using Edge for example.

**Comment by JoaoVictorDaijo** [comment]
> Hmm, I cannot reproduce it. A temporary workaround would be using Edge for example.

Headless mode works for other browsers too?

**Comment by LeagueOfPoro** [comment]
> Headless mode works for other browsers too?

yes

**Comment by JoaoVictorDaijo** [comment]
> > Headless mode works for other browsers too?
> 
> yes

That's fine then I can also 'fix' it by running as adm. I think the issue can be closed.
