### ISSUE TITLE
[WinError 87] The parameter is incorrect CANNOT CREATE A WEBDRIVER!

### ISSUE THREAD

**Issue by josephisticated** [LeagueOfPoro/EsportsCapsuleFarmer#73]
It was working fine a couple hours ago, now the edge driver is gone and it's not working.

**Comment by LeagueOfPoro** [comment]
Try to run it again and check if you have the latest Edge (106 as of now)

**Comment by josephisticated** [comment]
it works now, but it didn't back then, I even checked the edge version immediately as I had this problem on chrome too, guess microsoft pushed the update a bit late.
