### ISSUE TITLE
Multiple account issue

### ISSUE THREAD

**Issue by Conirefle** [LeagueOfPoro/EsportsCapsuleFarmer#75]
The multiple account bat is not working for me. After creting the 3 config file and configured as the syntax want, it opens all the 3 but after a seconds close 2 instance and neither the autologin or the headless mod works.

**Comment by LeagueOfPoro** [comment]
Did you try to run it again?

**Comment by Conirefle** [comment]
Yes i tried to rerunit. 
Still crashes.
Do you need some log file? And if yes how i can retrive it?

**Comment by Conirefle** [comment]
Okay i downloaded the last release and now it works flawlessly
