### ISSUE TITLE
[bug]ENGLISH[oce] No match

### ISSUE THREAD

**Issue by FrostyPowerUp** [LeagueOfPoro/EsportsCapsuleFarmer#9]
Issue with OCE redirecting to lolesports.com/schedule .
OCE doesn't use the main page and automatically redirects to the schedule where element "a.match.live" is not present so no match are found by the tool.
Changing language to either EUW or NA before logging in fix's the bug. 
The automatic login and headless will not work with OCE region.

**Comment by LeagueOfPoro** [comment]
I will look into that tomorrow, thank you

**Comment by auroraisluna** [comment]
@FrostyPowerUp Fork the repo and create a PR so the changes can be edited and merged easily :)
