### ISSUE TITLE
Error in headless mode 

### ISSUE THREAD

**Issue by Synertric** [LeagueOfPoro/EsportsCapsuleFarmer#96]
Soo this is the error

![1](https://user-images.githubusercontent.com/122853723/212814830-4c1cd186-cd7e-4d87-9dbb-80db03d7775a.png)

**Comment by Synertric** [comment]
But.. its kinda working? idk
![image](https://user-images.githubusercontent.com/122853723/212815151-32a26026-b1ad-4266-8b0e-9f5d079744cc.png)

**Comment by renzynx** [comment]
@Synertric it is nothing to be worried just ignore it

**Comment by Synertric** [comment]
Okay, ty!
